#!/usr/bin/env python

import sys

from kmerutils import FastAReader, canonize_cycle

K = 41

def main():
    if len(sys.argv) != 2:
        print("Usage: %s infile" % sys.argv[0])
        sys.exit(2)
    
    reader = FastAReader(sys.argv[1])
    
    for contig in reader.contigs():
        print canonize_cycle(contig)

if __name__ == '__main__':
    main()
