#!/usr/bin/env python

import sys

K = 41

def main():
    if len(sys.argv) != 2:
        print 'Usage: %s kmer' % sys.arv[1]
        sys.exit(2)
    
    read = sys.argv[1]
    for i in range(len(read) - K + 1):
        print read[i:i + K]

if __name__ == '__main__':
    main()
